weights: "CompVis/stable-diffusion-v1-4"
eval_weights: "clip-vit-base-patch32"
prompts: "data_vizwiz/val.json"
random_seed: 0
prompt_max_len: 77
in_channels: 4
height: 512
width: 512
scale_size: 8
num_inference_steps: 50
guidance_scale: 7.5
prompt_samples: 10
num_train_timesteps: 1000
embed_hidden_size: 768
